### ISSUE TITLE
[Bug] Cannot preform hybrid search, query by vector does not take sparse vector value

### ISSUE THREAD

**Issue by max-tano** [pinecone-io/pinecone-ts-client#218]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

![Screenshot 2024-05-22 at 3 10 48 PM](https://github.com/pinecone-io/pinecone-ts-client/assets/146136444/cc3590f0-557d-4e4c-9e39-0b16cd57a7a6)

Query by vector values only takes in the RecordValues type and not the RecordSparseValues type shown below
![Screenshot 2024-05-22 at 3 11 52 PM](https://github.com/pinecone-io/pinecone-ts-client/assets/146136444/d67105fe-7cf7-4ef1-9d57-2ec247f448e6)

Im able to do this query in python but does not seem like functionality is in typescript client yet?

### Expected Behavior

I should be able to send in both dense and sparse vector values to preform hybrid search

### Steps To Reproduce

https://docs.pinecone.io/guides/data/query-sparse-dense-vectors

following that but in typescript, using this version    "@pinecone-database/pinecone": "^2.0.1"

### Environment

```markdown
- **OS**:
- **Language version**:
- **Pinecone client version**:
```

**Comment by max-tano** [comment]
Edit can confirm it doesnt work in the latest version 2.2.1

**Comment by mcpaddy** [comment]
Hello @max-tano,

Thank you for raising this issue. I have tried to reproduce it, and it works successfully using `pinecone@2.2.0`.

Here is my code snippet:

```
import { Pinecone } from '@pinecone-database/pinecone';

const pc = new Pinecone({ apiKey: "API KEY" })
const index = pc.index("sparse")

const vectors = [
      {
              id: 'vec1',
              values: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8],
              sparseValues: {
                          indices: [1, 5],
                          values: [0.5, 0.5]
                      },
              metadata: {genre: 'drama'},
            },
      {
              id: 'vec2',
              values: [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
              metadata: {'genre': 'action'},
              sparseValues: {
                          indices: [5, 6],
                          values: [0.4, 0.5]
                      }
            }
]

await index.upsert(vectors);
console.log(await index.query({topK: 10,
  vector: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
  sparseVector: {'indices': [1, 5], 'values': [0.3, 0.5]}
  }));
```

**Comment by mcpaddy** [comment]
Hello all,

To follow up, we have reproduced the issue. 

```
sparse.ts:56:3 - error TS2353: Object literal may only specify known properties, and 'sparseVector' does not exist in type 'QueryOptions'.                    
                                                                                                                                                              
56   sparseVector: {'indices': [6, 5], 'values': [0.3, 0.5]},                                                                                                 
     ~~~~~~~~~~~~                                                               
```

The error happens when compiling TypeScript. Which is why my JS code above works fine.

We have a [Pull request](https://github.com/pinecone-io/pinecone-ts-client/pull/236) in flight for this issue.
